### ISSUE TITLE
Error: Cannot find module './bundle'

### ISSUE THREAD

**Issue by dporf** [udamir/api-ref-bundler#300]
Cannot use api-ref-bundler 0.4.2, when I import bundle
`import { bundle } from 'api-ref-bundler'`
I get the following:
`Error: Cannot find module './bundle'`
0.4.0 works well

**Comment by udamir** [comment]
try to import like this:
```
import ApiBundler from 'api-ref-bundler'

const bundled = await ApiBundler.bundle(...)
```

**Comment by dporf** [comment]
Unfornunately that doesn't help, I get the same error

**Comment by deiferni** [comment]
hello @udamir 

We have stumbled upon the same issue today. We have inspected the package on npm and it might be that certain `*.js` files are missing from the package?  E.g. there is no `bundle.js` present but it is required by the `index.mjs`/`index.cjs` files.

In version `0.4.0` they are present, so we also currently stick to that version.
Maybe switching to `rollup` in https://github.com/udamir/api-ref-bundler/commit/33f164242cf7c9686f23aae72f7424af7db9ed53 has tripped up something in the build/release so that the ts files are not compiled correctly 🤔?

**Comment by udamir** [comment]
please check api-ref-bundler@0.4.3

**Comment by deiferni** [comment]
Version `0.4.3` works for me, thanks!

**Comment by dporf** [comment]
Tested OK
